name: Tests
on:
  pull_request:
    type: [opened, reopened]

permissions: read-all

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      # Set up Flutter
      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.2'
          channel: 'stable'
      - run: flutter doctor

      # Checkout release branch
      - name: Checking out codebase
        uses: actions/checkout@v4
      - run: echo "sha=${{ github.event.pull_request.head.sha }}"
#      - run: git checkout develop
#      - run: flutter pub get
#      - run: flutter test