name: Tests
on:
  push:
    branches:
      - release-*


permissions: read-all

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    uses: subosito/flutter-action@v2
    with:
      flutter-version: '3.1.0'
      channel: 'stable'
    run: flutter --version