name: Tests
on:
  push:
    branches:
      - release-*


permissions: read-all

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      # Set up Flutter
      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.2'
          channel: 'stable'
      - run: flutter doctor

      # Checkout codebase
      - name: Checking out codebase
        uses: actions/checkout
      - run: git branch